global:
  scrape_interval: 15s
  external_labels:
    workload: "olap-sort"
    sharding: "sharded"
    vitess_ref: "b451c7e6f9035d3ad50e5eef219dc36cf7ca0474"
scrape_configs:
  - job_name: vttablet-1001
    static_configs:
      - targets: ["mysql-1001:16011", "mysql-1001:9104"]
remote_write:
  - url: http://prometheus:9090/api/v1/write
