global:
  scrape_interval: 15s
  external_labels:
    workload: "oltp"
    sharding: "sharded"
    vitess_ref: "main"
scrape_configs:
  - job_name: vttablet-1001
    static_configs:
      - targets: ["mysql-1001:16011", "mysql-1001:9104"]
remote_write:
  - url: http://prometheus:9090/api/v1/write
