[build]
bin = "./main admin --config ./config/dev/config.yaml --secrets ./config/dev/secrets.yaml --admin-port=9090 --admin-vitess-path=../"
cmd = "go build ./go/main.go"
main = "main.go"
include_ext = ["go", "html"]
exclude_dir = ["website", "tmp"]

[log]
level = "debug"

[misc]
clean_on_exit = true
