[build]
bin = "./main api --config ./config/dev/config.yaml --secrets ./config/dev/secrets.yaml --web-port=9090"
cmd = "go build ./go/main.go"
main = "main.go"
include_ext = ["go", "html"]
exclude_dir = ["website", "tmp"]

[log]
level = "debug"

[misc]
clean_on_exit = true
