#!/usr/bin/env python

# ------------------------------------------------------------------------------------------------------------------------------------
# Copyright 2021 The Vitess Authors.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#    http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# demonstrates to:
#   - Creates Cli to interact with the benchmarks
#      1. --runall: runs OLTP and TPCC
#      2. --commit: specify commit hash or branch name
#      3. --run-tpcc: Runs TPCC
#      4. --run-oltp: Runs OLTP
#      5. --inventory-file: Set inventory file to run
# -------------------------------------------------------------------------------------------------------------------------------------
import click
import uuid
from run_benchmark import run_tasks
from config import set_inventory_file


# ----------------------------------------------- CLI flags --------------------------------------------------------

@click.command()
@click.option("--run-all", is_flag=True, help="runs OLTP and TPCC")
@click.option("--commit",  "-c", help="specify commit hash or branch name ")
@click.option("--source",  "-s", help="mention the source from where the cli is called")
@click.option("--run-tpcc", "-runt",is_flag=True, help="Runs TPCC")
@click.option("--run-oltp", "-runo",is_flag=True, help="Runs OLTP")
@click.option("--inventory-file",  "-invf", help="mention inventory file to call")

# -------------------------------------------------------------------------------------------------------------------
# -------------------------------------- Actions when flags are called ----------------------------------------------

def main(run_all,commit,source,run_tpcc,run_oltp,inventory_file):

    run_id = str(uuid.uuid4())

    if inventory_file:
       set_inventory_file(inventory_file)        

    if run_all and commit and source:
           tasks = ["oltp", "tpcc"]

    elif run_tpcc and commit and source:
          tasks = ["tpcc"]

    elif run_oltp and commit and source:
          tasks = ["oltp"]

    # Display --help information when no flag is called
    else:
        ctx = click.get_current_context()
        click.echo(ctx.get_help())

    run_tasks(commit, run_id, source, tasks)
# -------------------------------------------------------------------------------------------------------------------

if __name__ == "__main__":
    main()
