#!/bin/bash

#alias activate="benchmark/bin/activate"

#Directory of ansible files
cd ansible/

#Run ansible script (Runs for all except sysbench)
ANSIBLE_HOST_KEY_CHECKING=False /root/arewefastyet/benchmark/bin/ansible-playbook --private-key=/root/.ssh/id_rsa -i $1 full.yml -u root -e provision=True -e clean=True
