{
 "title": "Vitess / Cluster Overview (auto-generated)",
 "description": "Vitess cluster overview",
 "tags": [
  "vitess-mixin",
  "overview",
  "cluster"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1m,5m,10m,30m,1h,6h,12h" },
   {
    "name": "region",
    "label": "Region",
    "query": "label_values(vtctld_build_number{job=\"vitess-vtctld\"}, region)"
   }
  ]
 },
 "panels": [
  { "title": "Top level", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Query success - vtgate",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 - sum(rate(vtgate_api_error_counts{region=\"$region\", job=\"vitess-vtgate\"}[$interval])) / (sum(rate(vtgate_api_error_counts{region=\"$region\", job=\"vitess-vtgate\"}[$interval])) + sum(rate(vtgate_api_count{region=\"$region\", job=\"vitess-vtgate\"}[$interval])))\n"
    }
   ]
  },
  {
   "title": "Query success - vttablet",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 - (sum(rate(vttablet_errors{region=\"$region\", job=\"vitess-vttablet\"}[$interval])) / (sum(rate(vttablet_errors{region=\"$region\", job=\"vitess-vttablet\"}[$interval])) + sum(rate(vttablet_query_counts{region=\"$region\", job=\"vitess-vttablet\"}[$interval]))))"
    }
   ]
  },
  {
   "title": "QPS - vtgate",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(vtgate_api_count{region=\"$region\", job=\"vitess-vtgate\"}[$interval]))"
    }
   ]
  },
  {
   "title": "QPS - vttablet",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(vttablet_query_counts{region=\"$region\", job=\"vitess-vttablet\"}[$interval]))"
    }
   ]
  },
  {
   "title": "QPS - MySQL",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_queries{region=\"$region\", job=\"mysql\"}[$interval])) "
    }
   ]
  },
  {
   "title": "keyspace",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(vttablet_tablet_state{region=\"$region\", job=\"vitess-vttablet\"}) by (keyspace))"
    }
   ]
  },
  {
   "title": "shard",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(vttablet_tablet_state{region=\"$region\", job=\"vitess-vttablet\"}) by (keyspace, shard))"
    }
   ]
  },
  {
   "title": "vtgate",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(up{region=\"$region\", job=\"vitess-vtgate\"})"
    }
   ]
  },
  {
   "title": "vttablet",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(up{region=\"$region\", job=\"vitess-vttablet\"})"
    }
   ]
  },
  {
   "title": "vtctld",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(up{region=\"$region\", job=\"vitess-vtctld\"})"
    }
   ]
  },
  {
   "title": "vtworker",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(up{region=\"$region\", job=\"vitess-vtworker\"})"
    }
   ]
  },
  {
   "title": "RED (Requests / Error rate / Duration)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vtgate_queries_processed_by_table{region=\"$region\", job=\"vitess-vtgate\"}[$interval]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vtgate_api_error_counts{region=\"$region\", job=\"vitess-vtgate\"}[$interval])) /  sum(rate(vtgate_api_count{region=\"$region\", job=\"vitess-vtgate\"}[$interval]))",
     "legendFormat": "Error rate"
    }
   ]
  },
  {
   "title": "Duration 99th quantile",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(vtgate_api_bucket{region=\"$region\", job=\"vitess-vtgate\"}[$interval])) by (le))",
     "legendFormat": "Duration"
    }
   ]
  },
  {
   "title": "Requests (by keyspace)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vtgate_queries_processed_by_table{region=\"$region\", job=\"vitess-vtgate\"}[$interval])) by (keyspace)",
     "legendFormat": "{{keyspace}}"
    }
   ]
  },
  {
   "title": "Error rate (by keyspace)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vtgate_api_error_counts{region=\"$region\", job=\"vitess-vtgate\"}[$interval])) by (keyspace) /  sum(rate(vtgate_api_count{region=\"$region\", job=\"vitess-vtgate\"}[$interval])) by (keyspace)",
     "legendFormat": "{{keyspace}}"
    }
   ]
  },
  {
   "title": "Duration 99th quantile (by keyspace)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(vtgate_api_bucket{region=\"$region\", job=\"vitess-vtgate\"}[$interval])) by (keyspace, le))",
     "legendFormat": "{{keyspace}}"
    }
   ]
  },
  { "title": "vttablet", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Query pool: min connections available (by keyspace)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(vttablet_conn_pool_available{region=\"$region\", job=\"vitess-vttablet\"}) by (keyspace)",
     "legendFormat": "{{keyspace}}"
    }
   ]
  },
  {
   "title": "Transaction pool: min connections available (by keyspace)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(vttablet_transaction_pool_available{region=\"$region\", job=\"vitess-vttablet\"}) by (keyspace)",
     "legendFormat": "{{keyspace}}"
    }
   ]
  },
  {
   "title": "Count of serving tablets (by keyspace)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(vttablet_tablet_server_state{region=\"$region\", job=\"vitess-vttablet\", name=\"SERVING\"}) by (keyspace)",
     "legendFormat": "{{keyspace}}"
    }
   ]
  },
  { "title": "MySQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Slow queries > 0 (by keyspace)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_slow_queries{region=\"$region\", job=\"mysql\"}[$interval])) by (keyspace) > 0",
     "legendFormat": "{{keyspace}}"
    }
   ]
  },
  {
   "title": "Replication lag > 0 (by keyspace)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(mysql_slave_status_seconds_behind_master{region=\"$region\", job=\"mysql\"}) by (keyspace) > 0",
     "legendFormat": "{{keyspace}}"
    }
   ]
  },
  {
   "title": "Semi-sync replication avg wait time (by keyspace)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_rpl_semi_sync_master_tx_avg_wait_time{region=\"$region\", job=\"mysql\"}[$interval])) by (keyspace)",
     "legendFormat": "{{keyspace}}"
    }
   ]
  }
 ]
}