{
 "title": "Compare Benchmark",
 "time": { "from": "2021-04-27T16:50:12.091Z", "to": "2021-04-27T17:32:34.738Z" },
 "templating": {
  "list": [
   { "name": "exec_uuid_1", "label": "exec_uuid_1", "query": { "query": "label_values(exec_uuid)" } },
   { "name": "exec_uuid_2", "label": "exec_uuid_2", "query": { "query": "label_values(exec_uuid)" } },
   { "name": "time_shift", "query": "0m" },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Busy",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{exec_uuid=\"$exec_uuid_1\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',exec_uuid=\"$exec_uuid_1\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{exec_uuid=\"$exec_uuid_1\"}) by (cpu))",
     "legendFormat": "CPU busy Exec UUID 1"
    },
    {
     "expr": "(((count(count(node_cpu_seconds_total{exec_uuid=\"$exec_uuid_2\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',exec_uuid=\"$exec_uuid_2\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{exec_uuid=\"$exec_uuid_2\"}) by (cpu))",
     "legendFormat": "CPU busy Exec UUID 2"
    }
   ]
  },
  {
   "title": "Average CPU busy",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{exec_uuid=\"$exec_uuid_1\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',exec_uuid=\"$exec_uuid_1\"}[1m])))) * 100) / count(count(node_cpu_seconds_total{exec_uuid=\"$exec_uuid_1\"}) by (cpu))",
     "legendFormat": "Exec UUID 1"
    },
    {
     "expr": "(((count(count(node_cpu_seconds_total{exec_uuid=\"$exec_uuid_2\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',exec_uuid=\"$exec_uuid_2\"}[1m])))) * 100) / count(count(node_cpu_seconds_total{exec_uuid=\"$exec_uuid_2\"}) by (cpu))",
     "legendFormat": "Exec UUID 2"
    }
   ]
  },
  {
   "title": "Average CPU busy difference",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{exec_uuid=\"$exec_uuid_2\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',exec_uuid=\"$exec_uuid_2\"}[1m])))) * 100) / count(count(node_cpu_seconds_total{exec_uuid=\"$exec_uuid_2\"}) by (cpu))-(((count(count(node_cpu_seconds_total{exec_uuid=\"$exec_uuid_1\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',exec_uuid=\"$exec_uuid_1\"}[1m])))) * 100) / count(count(node_cpu_seconds_total{exec_uuid=\"$exec_uuid_1\"}) by (cpu))",
     "legendFormat": "Exec UUID 1"
    }
   ]
  },
  {
   "title": "CPU busy duration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_cpu_seconds_total{mode!=\"idle\",exec_uuid=\"$exec_uuid_1\"})",
     "legendFormat": "Exec UUID 1"
    },
    {
     "expr": "sum(node_cpu_seconds_total{mode!=\"idle\",exec_uuid=\"$exec_uuid_2\"})",
     "legendFormat": "Exec UUID 2"
    }
   ]
  },
  {
   "title": "CPU busy duration difference %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(node_cpu_seconds_total{mode!=\"idle\",exec_uuid=\"$exec_uuid_2\"}[1d]))-sum(increase(node_cpu_seconds_total{mode!=\"idle\",exec_uuid=\"$exec_uuid_1\"}[1d])))/sum(increase(node_cpu_seconds_total{mode!=\"idle\",exec_uuid=\"$exec_uuid_1\"}[1d]))*100",
     "legendFormat": "Exec UUID 1"
    }
   ]
  },
  {
   "title": "CPU duration VTGate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(process_cpu_seconds_total{exec_uuid=\"$exec_uuid_1\", component=\"vtgate\"})",
     "legendFormat": "Exec UUID 1"
    },
    {
     "expr": "sum(process_cpu_seconds_total{exec_uuid=\"$exec_uuid_2\", component=\"vtgate\"})",
     "legendFormat": "Exec UUID 2"
    }
   ]
  },
  {
   "title": "CPU duration VTGate difference",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(process_cpu_seconds_total{component=\"vtgate\", exec_uuid=\"$exec_uuid_2\"}[24h]))-sum(increase(process_cpu_seconds_total{component=\"vtgate\", exec_uuid=\"$exec_uuid_1\"}[24h]))\n",
     "legendFormat": "Time Difference Between Exec UUID 1 and Exec UUID 2"
    }
   ]
  },
  {
   "title": "CPU duration VTGate difference",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(process_cpu_seconds_total{component=\"vtgate\", exec_uuid=\"$exec_uuid_2\"}[24h]))-sum(increase(process_cpu_seconds_total{component=\"vtgate\", exec_uuid=\"$exec_uuid_1\"}[24h])))/sum(increase(process_cpu_seconds_total{component=\"vtgate\", exec_uuid=\"$exec_uuid_2\"}[24h]))*100",
     "legendFormat": "Exec UUID 1"
    }
   ]
  },
  {
   "title": "Time spent Exec UUID 1",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 2, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(process_cpu_seconds_total{exec_uuid=\"$exec_uuid_1\", component=\"vtgate\"})",
     "legendFormat": "VTGate"
    },
    {
     "expr": "sum(process_cpu_seconds_total{exec_uuid=\"$exec_uuid_1\", component=\"vttablet\"})",
     "legendFormat": "VTTablet"
    }
   ]
  },
  {
   "title": "Time spent Exec UUID 2",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 2, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(process_cpu_seconds_total{exec_uuid=\"$exec_uuid_2\", component=\"vtgate\"})",
     "legendFormat": "VTGate"
    },
    {
     "expr": "sum(process_cpu_seconds_total{exec_uuid=\"$exec_uuid_2\", component=\"vttablet\"})",
     "legendFormat": "VTTablet"
    }
   ]
  },
  {
   "title": "CPU busy duration difference",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_cpu_seconds_total{mode!=\"idle\",exec_uuid=\"$exec_uuid_2\"}[1d]))-sum(increase(node_cpu_seconds_total{mode!=\"idle\",exec_uuid=\"$exec_uuid_1\"}[1d]))",
     "legendFormat": "Exec UUID 1"
    }
   ]
  },
  {
   "title": "CPU duration VTTablet",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(process_cpu_seconds_total{exec_uuid=\"$exec_uuid_1\", component=\"vttablet\"})",
     "legendFormat": "Exec UUID 1"
    },
    {
     "expr": "sum(process_cpu_seconds_total{exec_uuid=\"$exec_uuid_2\", component=\"vttablet\"})",
     "legendFormat": "Exec UUID 2"
    }
   ]
  },
  {
   "title": "CPU duration VTTablet difference",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(process_cpu_seconds_total{exec_uuid=\"$exec_uuid_2\", component=\"vttablet\"}[1d]))-sum(increase(process_cpu_seconds_total{exec_uuid=\"$exec_uuid_1\", component=\"vttablet\"}[1d]))",
     "legendFormat": "Exec UUID 1"
    }
   ]
  },
  {
   "title": "CPU duration VTTablet difference",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(process_cpu_seconds_total{exec_uuid=\"$exec_uuid_2\", component=\"vttablet\"})-sum(process_cpu_seconds_total{exec_uuid=\"$exec_uuid_1\", component=\"vttablet\"}))/sum(process_cpu_seconds_total{exec_uuid=\"$exec_uuid_1\", component=\"vttablet\"})*100"
    }
   ]
  },
  { "title": "QPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "VTGate average QPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(vtgate_api_count{exec_uuid=\"$exec_uuid_1\"}[1m]))",
     "legendFormat": "QPS Exec UUID 1"
    },
    {
     "expr": "avg(rate(vtgate_api_count{exec_uuid=\"$exec_uuid_2\"}[1m]))",
     "legendFormat": "QPS Exec UUID 2"
    }
   ]
  },
  {
   "title": "VTGate Queries Processed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vtgate_queries_processed{exec_uuid=\"$exec_uuid_1\"})"
    },
    {
     "expr": "sum(vtgate_queries_processed{exec_uuid=\"$exec_uuid_2\"})"
    }
   ]
  }
 ]
}