{
 "title": "Vitess / Keyspace Overview (auto-generated)",
 "description": "General keyspace overview",
 "tags": [
  "vitess-mixin",
  "overview",
  "keyspace"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1m,5m,10m,30m,1h,6h,12h" },
   {
    "name": "region",
    "label": "Region",
    "query": "label_values(vtctld_build_number{job=\"vitess-vtctld\"}, region)"
   },
   {
    "name": "keyspace",
    "label": "Keyspace",
    "query": "label_values(vttablet_build_number{job=\"vitess-vttablet\", region=\"$region\"}, keyspace)"
   },
   {
    "name": "table",
    "label": "Table",
    "query": "label_values(vtgate_queries_processed_by_table{job=\"vitess-vtgate\", region=\"$region\", keyspace=\"$keyspace\"}, table)"
   }
  ]
 },
 "panels": [
  { "title": "vtgate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "QPS (by table)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vtgate_queries_processed_by_table{region=\"$region\", job=\"vitess-vtgate\", keyspace=\"$keyspace\", table=~\"$table\"}[$interval])) by (table)",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "QPS (by plan type)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vtgate_queries_processed_by_table{region=\"$region\", job=\"vitess-vtgate\", keyspace=\"$keyspace\", table=~\"$table\"}[$interval])) by (plan)",
     "legendFormat": "{{plan}}"
    }
   ]
  },
  {
   "title": "Query success rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - sum(rate(vtgate_api_error_counts{region=\"$region\", job=\"vitess-vtgate\", keyspace=\"$keyspace\", table=~\"$table\"}[$interval])) / (sum(rate(vtgate_api_error_counts{region=\"$region\", job=\"vitess-vtgate\", keyspace=\"$keyspace\", table=~\"$table\"}[$interval])) + sum(rate(vtgate_api_count{region=\"$region\", job=\"vitess-vtgate\", keyspace=\"$keyspace\", table=~\"$table\"}[$interval]))) * 100",
     "legendFormat": "Success rate"
    },
    {
     "expr": "sum(rate(vtgate_api_error_counts{region=\"$region\", job=\"vitess-vtgate\", keyspace=\"$keyspace\", table=~\"$table\"}[$interval]))",
     "legendFormat": "Error count"
    }
   ]
  },
  { "title": "vttablet", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "QPS (by table)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vttablet_query_counts{region=\"$region\", job=\"vitess-vttablet\", keyspace=\"$keyspace\", table=~\"$table\"}[$interval])) by (table)",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "QPS (by plan type)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vttablet_query_counts{region=\"$region\", job=\"vitess-vttablet\", keyspace=\"$keyspace\", table=~\"$table\"}[$interval])) by (plan)",
     "legendFormat": "{{plan}}"
    }
   ]
  },
  {
   "title": "Query success rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (sum(rate(vttablet_errors{region=\"$region\", job=\"vitess-vttablet\", keyspace=\"$keyspace\", table=~\"$table\"}[$interval])) / (sum(rate(vttablet_errors{region=\"$region\", job=\"vitess-vttablet\", keyspace=\"$keyspace\", table=~\"$table\"}[$interval])) + sum(rate(vttablet_query_counts{region=\"$region\", job=\"vitess-vttablet\", keyspace=\"$keyspace\", table=~\"$table\"}[$interval])))) * 100",
     "legendFormat": "Success rate"
    },
    {
     "expr": "sum(rate(vttablet_errors{region=\"$region\", job=\"vitess-vttablet\", keyspace=\"$keyspace\", table=~\"$table\"}[$interval]))",
     "legendFormat": "Error count"
    }
   ]
  },
  {
   "title": "Query/Transaction timings (table filter doesn't apply)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }
  },
  {
   "title": "Query time (avg)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum (rate(vttablet_queries_sum{region=\"$region\", job=\"vitess-vttablet\", keyspace=\"$keyspace\"}[$interval])) /\nsum (rate(vttablet_queries_count{region=\"$region\", job=\"vitess-vttablet\", keyspace=\"$keyspace\"}[$interval]))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Query time (p50)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(vttablet_queries_bucket{region=\"$region\", job=\"vitess-vttablet\", keyspace=\"$keyspace\"}[$interval])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Query time (p95)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(vttablet_queries_bucket{region=\"$region\", job=\"vitess-vttablet\", keyspace=\"$keyspace\"}[$interval])) by (le))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Query time (p999)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(vttablet_queries_bucket{region=\"$region\", job=\"vitess-vttablet\", keyspace=\"$keyspace\"}[$interval])) by (le))",
     "legendFormat": "p999"
    }
   ]
  },
  {
   "title": "Transaction time (avg)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum (rate(vttablet_transactions_sum{region=\"$region\", job=\"vitess-vttablet\", keyspace=\"$keyspace\"}[$interval])) /\nsum (rate(vttablet_transactions_count{region=\"$region\", job=\"vitess-vttablet\", keyspace=\"$keyspace\"}[$interval]))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Transaction time (p50)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(vttablet_transactions_bucket{region=\"$region\", job=\"vitess-vttablet\", keyspace=\"$keyspace\"}[$interval])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Transaction time (p95)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(vttablet_transactions_bucket{region=\"$region\", job=\"vitess-vttablet\", keyspace=\"$keyspace\"}[$interval])) by (le))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Transaction time (p999)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(vttablet_transactions_bucket{region=\"$region\", job=\"vitess-vttablet\", keyspace=\"$keyspace\"}[$interval])) by (le))",
     "legendFormat": "p999"
    }
   ]
  },
  {
   "title": "Query timings heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum(rate(vttablet_queries_bucket{region=\"$region\", job=\"vitess-vttablet\", keyspace=\"$keyspace\"}[$interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Transaction timings heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "sum(rate(vttablet_queries_bucket{region=\"$region\", job=\"vitess-vttablet\", keyspace=\"$keyspace\"}[$interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}