# Copyright 2021 The Vitess Authors.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#    http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Debian Install
  block:
    - name: Add Mysql apt key
      become: yes
      become_user: root
      apt_key:
        keyserver: '{{ mysql_apt_keyserver }}'
        id: '{{ mysql_apt_key_id }}'
        state: present
        register: apt_key_install
        until: apt_key_install is succeeded

    - name: Copy mysql.list
      become: yes
      become_user: root
      template:
        src: 'mysql.list.j2'
        dest: /etc/apt/sources.list.d/mysql.list
        owner: root
        group: root
        mode: 0644
    - name: Register packages to install
      set_fact:
        mysql_packages:
          - mysql-server
          - python-pymysql
  when: ansible_os_family == 'Debian'
- name: AWS Install
  block:
    - name: Add repository
      yum:
        name='https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm'

    - name: Enable Repository
      shell: |
        yum-config-manager --enable epel

    - name: Install the MySQL 8 repository
      yum:
        name='{{ mysql_repo_7_rpm }}'
    - name: Register packages to install
      set_fact:
        mysql_packages:
          - mysql-server
          - python2-PyMySQL
  when: ansible_os_family == 'RedHat' and ansible_distribution == 'Amazon'

- name: RedHat Install
  block:
    - name: Add repository
      yum_repository:
        name: epel
        description: EPEL YUM repo
        # baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
        metalink: https://mirrors.fedoraproject.org/metalink?repo=epel-$releasever&arch=$basearch&infra=$infra&content=$contentdir
        gpgcheck: false

    - name: Install the MySQL 8 repository
      yum:
        name='{{ mysql_repo_rpm }}'
    - name: Register packages to install
      set_fact:
        mysql_packages:
          - mysql-server
          - python2-PyMySQL
  when: ansible_os_family == 'RedHat' and ansible_distribution != 'Amazon'

- name: Install Mysql
  package:
    name: '{{ mysql_packages }}'
    state: present
    update_cache: true
  register: task_result
  until: task_result is succeeded
