# Copyright 2021 The Vitess Authors.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#    http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Check for installation of etcd
  become: true
  become_user: root
  ansible.builtin.stat:
    path: "{{ etcd_install_dir }}/{{ etcd_name }}"
  changed_when: false
  register: etcd_binary_dir

- name: Download and install etcd
  when: not etcd_binary_dir.stat.exists
  become: true
  become_user: root
  block:
    - name: Download etcd
      ansible.builtin.get_url:
        url: "{{ etcd_archive_url }}"
        dest: /tmp/{{ etcd_archive }}
        checksum: "{{ etcd_checksum }}"
        timeout: "{{ etcd_download_timeout_seconds }}"
    - name: Unachive etcd
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: /tmp/{{ etcd_archive }}
        dest: "{{ etcd_install_dir }}"
        creates: "{{ etcd_install_dir }}/{{ etcd_name }}"
  always:
    - name: Delete archive
      ansible.builtin.file:
        path: /tmp/{{ etcd_archive }}
        state: absent

- name: Link etcd and etcdctl
  become: true
  become_user: root
  ansible.builtin.file:
    src: "{{ etcd_install_dir }}/{{ etcd_name }}/{{ item }}"
    dest: "{{ etcd_install_dir }}/{{ item }}"
    state: link
  with_items:
    - etcd{{ etcd_exe_suffix | default("") }}
    - etcdctl{{ etcd_exe_suffix | default("") }}
