#!/bin/bash

# Copyright 2021 The Vitess Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Unfortunately golangci-lint does not work well on checking just modified files.
# We will enable it for everything here, but with most of the linters disabled.
# See: https://github.com/vitessio/vitess/issues/5503

gofiles=$(git diff --cached --name-only --diff-filter=ACM | grep '^go/.*\.go$')

# xargs -n1 because dirname on MacOS does not support multiple arguments.
gopackages=$(echo $gofiles | xargs -n1 dirname | sort -u)

GOLANGCI_LINT=$(command -v golangci-lint || true)

if [ -z "$GOLANGCI_LINT" ]; then
  echo "Downloading golangci-lint..."

  GOLANGCI_LINT="$(go env GOPATH)/bin/golangci-lint"

  GOBIN=$(go env GOPATH)/bin go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.12.2
fi

for gopackage in $gopackages
do
 echo "Linting $gopackage"
 "$GOLANGCI_LINT" run --fast "$gopackage"
done
