# Copyright 2021 The Vitess Authors.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#    http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: template out configs
  become: yes
  become_user: root
  with_items:
    - s: vttablet.conf
      d: '/etc/vitess/conf/vttablet-{{ tablet.id }}.conf'
    - s: extra_my.cnf
      d: '/etc/vitess/extra_my{{ tablet.id }}.cnf'
  template:
    src: '{{ item.s }}.j2'
    dest: '{{ item.d }}'
    owner: '{{ vitess_user }}'
    group: '{{ vitess_group }}'
    mode: '0644'

- name: start mysql
  become: yes
  become_user: root
  when:
    - enable_vttablet | bool
  service:
    name: '{{ item }}'
    enabled: yes
    state: started
  with_items:
    - 'mysqlctld@{{ tablet.id }}'
    - 'mysqld_exporter@{{ tablet.id }}'
  changed_when: false

- name: wait for mysql socket
  become: yes
  become_user: root
  when:
    - enable_vttablet | bool
  wait_for:
    path:  '{{ vitess_root }}/socket/mysql{{ tablet.id }}.sock'
    delay: 5
    timeout: 60
    state: present
    msg: "mysql socket needs to be present {{ vitess_root }}/socket/mysql{{ tablet.id }}.sock"
  ignore_errors: true

- name: wait for mysqlctl socket
  become: yes
  become_user: root
  when:
    - enable_vttablet | bool
  wait_for:
    path:  '{{ vitess_root }}/socket/mysqlctl{{ tablet.id }}.sock'
    delay: 5
    timeout: 60
    state: present
    msg: "mysqlctl socket needs to be present at {{ vitess_root }}/socket/mysqlctl{{ tablet.id }}.sock"
  ignore_errors: true

- name: start vttablet
  become: yes
  become_user: root
  when:
    - enable_vttablet | bool
  service:
    name: '{{ item }}'
    enabled: yes
    state: started
  with_items:
    - 'vttablet@{{ tablet.id }}'
  changed_when: false