# Copyright 2021 The Vitess Authors.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#    http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Run the sysbench TPC-C benchmark and report the results
---
- hosts: sysbench
  tasks:
    - name: Prepare sysbench
      when: provision is defined
      block:
        - name: Prepare sysbench
          shell: |
            sysbench --luajit-cmd=off --threads={{ tpcc_load_threads }} --time={{ tpcc_preparation_time }} \
                      --mysql-db=main --mysql-host=127.0.0.1 --mysql-port=3306 --db-ps-mode=disable --db-driver=mysql \
                      --report-interval=10 --mysql-ignore-errors=all --use_fk=0 --tables={{ tpcc_number_tables }} \
                      --scale={{ tpcc_warehouses }} ./tpcc.lua prepare
          args:
            chdir: /src/sysbench-tpcc/
          async: 86400
          poll: 0
          register: sysbench_prepare

        - name: Wait for Prepare sysbench
          async_status:
            jid: '{{ sysbench_prepare.ansible_job_id }}'
          register: job_result
          until: job_result.finished
          retries: 86400

    - name: ensure sysbench
      shell: |
        sysbench --luajit-cmd=off --threads={{ tpcc_load_threads//7 }} --time={{ tpcc_ensure_time }} \
                  --mysql-db=main --mysql-host=127.0.0.1 --mysql-port=3306 --db-ps-mode=disable --db-driver=mysql \
                  --report-interval=10 --mysql-ignore-errors=all --use_fk=0 --tables={{ tpcc_number_tables }} \
                  --scale={{ tpcc_warehouses }} ./tpcc.lua ensure
      args:
        chdir: /src/sysbench-tpcc/
      changed_when: false

    - name: Warm up sysbench
      shell: |
        sysbench --luajit-cmd=off --threads={{ tpcc_load_threads }} --time={{ tpcc_warmup_time }} \
                  --mysql-db=main --mysql-host=127.0.0.1 --mysql-port=3306 --db-ps-mode=disable --db-driver=mysql \
                  --mysql-ignore-errors=all --use_fk=0 --rand-type=uniform --verbosity=0 --report_json=yes \
                  --tables={{ tpcc_number_tables }} --scale={{ tpcc_warehouses }} ./tpcc.lua run > /tmp/warm_tpcc.json
      args:
        chdir: /src/sysbench-tpcc/
      changed_when: false

    - name: Run sysbench
      block:
       - name: Run the test
         shell: |
           sysbench --luajit-cmd=off --threads={{ tpcc_threads }} --time={{ tpcc_test_time }} \
                    --mysql-db=main --mysql-host=127.0.0.1 --mysql-port=3306 --db-ps-mode=disable \
                    --db-driver=mysql --mysql-ignore-errors=all --use_fk=0 --rand-type=uniform --verbosity=0 \
                    --report_json=yes --tables={{ tpcc_number_tables }} --scale={{ tpcc_warehouses }} ./tpcc.lua run > /tmp/tpcc.json
         args:
           chdir: /src/sysbench-tpcc/
         async: '{{ tpcc_test_time*2 }}'
         poll: 0
         register: sysbench_run
       - name: Wait for sysbench to finish
         async_status:
            jid: "{{ sysbench_run.ansible_job_id }}"
         register: job_result
         until: job_result.finished
         retries: '{{ tpcc_test_time*2 }}'
       - debug:
           msg: '{{ job_result }}'
