name: Ansible Lint

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
    - uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4.9.1
      with:
        python-version: '3.12'

    - name: Update pip
      run: |
        python -m pip install --upgrade pip

    - name: Set up virtualenv
      run: |
        pip3 install virtualenv
        virtualenv --python=python3.12 benchmark
        source benchmark/bin/activate
        pip install -r requirements.txt

    - name: Install ansible dependencies
      run: |
        source benchmark/bin/activate
        ansible-galaxy install -r ansible/requirements.yml

    - name: Lint Ansible Playbook
      uses: ansible/ansible-lint@a2bc8b8b13a80802215856c56823d85007d3baf5 # v25.12.2
      with:
        python_version: '3.12'
        requirements_file: ansible/requirements.yml
        args: "-x 301,302,303,305,306,204,208 ansible/"
