name: Golang Tidy

on: [push, pull_request]

jobs:

  build:
    name: Check go mod tidy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Set up Go
        uses: actions/setup-go@7b8cf10d4e4a01d4992d18a89f4d7dc5a3e6d6f4 # v4.3.0
        with:
          go-version-file: go.mod

      # https://github.com/vitessio/vitess/blob/b5177cd4d09f661350137ef46de2bd3e27949d2e/.github/workflows/gomod-tidy.yml#L17-L28
      - name: Run go mod tidy
        run: |
          set -e
          go mod tidy
          output=$(git status -s)
          if [ -z "${output}" ]; then
           exit 0
          fi
          echo 'We wish to maintain a tidy state for go mod. Please run `go mod tidy` on your branch, commit and push again.'
          echo 'Running `go mod tidy` on this CI test yields with the following changes:'
          echo "$output"
          exit 1
