# Copyright 2021 The Vitess Authors.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#    http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Ensure config directory
  become: true
  become_user: root
  with_items:
    - /etc/vitess/conf
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    owner: "{{ vitess_user }}"
    group: "{{ vitess_group }}"

- name: Reinstall systemd unit if needed
  ansible.builtin.include_tasks: systemd.yml
  when: arewefastyet_execution_workload is undefined or arewefastyet_execution_workload != 'micro'

- name: Check if there is a vtctld service
  ansible.builtin.command: service vtctld@{{ vitess_cell }} status
  register: vtctld_status
  failed_when: not(vtctld_status.rc == 3 or vtctld_status.rc == 4 or vtctld_status.rc == 0)

- name: Stop old vtctld
  become: true
  become_user: root
  ansible.builtin.service:
    name: vtctld@{{ vitess_cell }}
    enabled: false
    state: stopped
  changed_when: false
  when: vtctld_status.rc == 0
  failed_when: false

- name: Check if there is a cell service
  ansible.builtin.command: service cell@{{ vitess_cell }} status
  register: cell_status
  failed_when: not(vtctld_status.rc == 3 or cell_status.rc == 4 or cell_status.rc == 0)

- name: Stop old cell
  become: true
  become_user: root
  ansible.builtin.service:
    name: cell@{{ vitess_cell }}
    enabled: false
    state: stopped
  changed_when: false
  when: cell_status.rc == 0
  failed_when: false

- name: Remove old config
  become: true
  become_user: root
  with_items:
    - "/etc/vitess/conf/vtctld-{{ vitess_cell }}.conf"
    - "/etc/systemd/system/vtctld@.service"
    - "/etc/systemd/system/cell@.service"
  ansible.builtin.file:
    state: absent
    path: "{{ item }}"
  failed_when: false

- name: Systemctl daemon-reload
  become: true
  become_user: root
  ansible.builtin.systemd:
    daemon_reload: true
  failed_when: false

- name: Remove binary
  ansible.builtin.shell: rm -f $(which vtctld vtctl vtctlclient vtctldclient)
